#!/bin/bash

check_exit_status() {

	if [ $? -eq 0 ]
	then
		echo
		echo "Success"
		echo
	else
		echo
		echo "[ERROR] Process Failed!"
		echo
		
		read -p "The last command exited with an error. Exit script? (yes/no) " answer

            if [ "$answer" == "yes" ]
            then
                exit 1
            fi
	fi
}

greeting() {

	echo
	echo "Hello, $USER. I'm starting the update."
	echo
}

update() {

    sudo apt update;
	check_exit_status

    sudo apt upgrade -y;
	check_exit_status

    sudo apt full-upgrade -y;
	check_exit_status
}

housekeeping() {

	sudo apt autoremove -y;
	check_exit_status

	sudo apt clean -y;
	check_exit_status
}

leave() {

	echo
	echo "--------------------"
	echo "- Update Complete! -"
	echo "--------------------"
	echo
	exit
}

greeting
update
housekeeping
leave